#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 <<-EOSQL
    CREATE USER $BEACON_NETWORK_DB_USERNAME WITH ENCRYPTED PASSWORD '$BEACON_NETWORK_DB_PASSWORD';
    GRANT ALL ON SCHEMA public TO $BEACON_NETWORK_DB_USERNAME;
    CREATE DATABASE "$POSTGRES_BN_DATABASE" OWNER $BEACON_NETWORK_DB_USERNAME;
    CREATE USER $KC_DB_USERNAME WITH ENCRYPTED PASSWORD '$KC_DB_PASSWORD';
    GRANT ALL ON SCHEMA public TO $KC_DB_USERNAME;
    CREATE DATABASE "$POSTGRES_KC_DATABASE" OWNER $KC_DB_USERNAME;
EOSQL