networks:
  beacon-network:

x-environment: &env
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=postgres
  - POSTGRES_BN_DATABASE=beacon-network
  - BEACON_NETWORK_CONFIG_DIR=/wildfly/BEACON-INF
  - BEACON_NETWORK_DB_CONNECTION_URL=jdbc:postgresql://postgres:5432/beacon-network
  - BEACON_NETWORK_DB_USERNAME=beacon
  - BEACON_NETWORK_DB_PASSWORD=beacon
  - JBOSS_JAVA_SIZING=-XX:+UseContainerSupport -XX:MaxRAMPercentage=70.0 -Xms128m
  - BEACON_NETWORK_OIDC_ENDPOINT=${BEACON_NETWORK_OIDC_ENDPOINT}
  - BEACON_NETWORK_CLIENT_ID=${BEACON_NETWORK_CLIENT_ID}
  - BEACON_NETWORK_CLIENT_SECRET=${BEACON_NETWORK_CLIENT_SECRET}
services:
  postgres:
    image: postgres:17.5-alpine
    restart: always
    environment: *env
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    networks:
      - beacon-network
  wildfly:
    image: ghcr.io/elixir-europe/beacon-network-backend-oidc:v0.0.14-oidc
    container_name: "wildfly-beacon-network"
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./wildfly/BEACON-INF:/wildfly/BEACON-INF
    hostname: wildfly
    networks:
      - beacon-network
    ports:
      - '8080:8080'
      - '8009:8009'
      - '8443:8443'
    environment: *env
