version: '3.8'

networks:
  elixir-beacon-network:

x-environment: &env
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=postgres
  - POSTGRES_BN_DATABASE=beacon-network
  - BEACON_NETWORK_CONFIG_DIR=/wildfly/BEACON-INF
  - BEACON_NETWORK_DB_CONNECTION_URL=jdbc:postgresql://postgres-gdi-af-demo:5432/beacon-network
  - BEACON_NETWORK_DB_USERNAME=beacon
  - BEACON_NETWORK_DB_PASSWORD=beacon
  - JBOSS_JAVA_SIZING=-XX:+UseContainerSupport -XX:MaxRAMPercentage=70.0 -Xms128m
  - BEACON_NETWORK_OIDC_ENDPOINT=https://login.aai.lifescience-ri.eu/oidc/
  - BEACON_NETWORK_CLIENT_ID=
  - BEACON_NETWORK_CLIENT_SECRET=
  - BEACON_NETWORK_TOKEN_AUDIENCE='["client1", "https://beacon-network-backend-test.ega-archive.org"]'
  - BEACON_NETWORK_TOKEN_ISSUER=https://login.aai.lifescience-ri.eu/oidc
services:
  postgres-gdi-af-demo:
    image: postgres:16.0-alpine
    container_name: "gdi-bn-af-db-demo"
    restart: always
    environment: *env
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    networks:
      - elixir-beacon-network
  wildfly-gdi-af-demo:
    image: ghcr.io/elixir-europe/beacon-network-backend-snapshot:v0.0.15-snapshot
    container_name: "gdi-bn-af-server-demo"
    depends_on:
      - postgres-gdi-af-demo
    restart: always
    volumes:
      - ./wildfly/BEACON-INF:/wildfly/BEACON-INF
    hostname: wildfly
    networks:
      - elixir-beacon-network
    ports:
      - '8085:8080'
    environment: *env