version: '3.8'

networks:
  elixir-beacon-network:

x-environment: &env
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=postgres
  - POSTGRES_BN_DATABASE=beacon-network
  - BEACON_NETWORK_CONFIG_DIR=/wildfly/BEACON-INF
  - BEACON_NETWORK_DB_CONNECTION_URL=jdbc:postgresql://postgres-gdi-af-prod:5432/beacon-network
  - BEACON_NETWORK_DB_USERNAME=beacon
  - BEACON_NETWORK_DB_PASSWORD=beacon
  - JBOSS_JAVA_SIZING=-XX:+UseContainerSupport -XX:MaxRAMPercentage=70.0 -Xms128m
services:
  postgres-gdi-af-prod:
    image: postgres:16.0-alpine
    container_name: "gdi-bn-af-db-prod"
    restart: always
    environment: *env
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    networks:
      - elixir-beacon-network
  wildfly-gdi-af-prod:
    image: ghcr.io/elixir-europe/beacon-network-backend:latest
    container_name: "gdi-bn-af-server-prod"
    depends_on:
      - postgres-gdi-af-prod
    restart: always
    volumes:
      - ./wildfly/BEACON-INF:/wildfly/BEACON-INF
    hostname: wildfly
    networks:
      - elixir-beacon-network
    ports:
      - '8098:8080'
    environment: *env